name: Actions Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps: 
      - name: List files
        run: |
          pwd
          ls
          # useful variables
          echo $GITHUB_SHA # commit id
          echo $GITHUB_REPOSITORY # username & repository name
          echo #GITHUB_WORKSPACE # workspace directory, same as pwd
          echo "${{ github.token }}" # token that can be used for authentication
      - name: checkout
        uses: actions/checkout@v1
      - name: List files after checkout
        run: |
          pwd
          ls
      - name: Simple JS Action
        id: greet
        uses: actions/hello-world-javascript-action@v1 # after @ can be branch, version or commit ID, version or commit preferred as errors may be introduced in branches
        with:
          who-to-great: Marcus
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"
